name: Build MorseWriter

on:
  push:
    branches:
      - main
      - pynput
  pull_request:
    branches:
      - main
      - pynput

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean MorseCodeGUI.spec

      - name: Download Inno Setup
        run: |
          choco install innosetup --yes

      - name: Build Installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" MorseWriterInstaller.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: morsewriter-installer
          path: Output/MorseWriter-Installer.exe
