name: Build MorseWriter

on:
  push:
    branches:
      - main
      - pynput
  pull_request:
    branches:
      - main
      - pynput

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --clean MorseCodeGUI.spec

      - name: Download Inno Setup
        run: |
          choco install innosetup --yes

      - name: Build Installer
        run: |
          Start-Process -FilePath "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" -ArgumentList "MorseWriterInstaller.iss" -Wait

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: morsewriter-installer
          path: Output/MorseWriter-Installer.exe
